### ISSUE TITLE
Any chance to combine MMM logic with existing API scripts?

### ISSUE THREAD

**Issue by phylll** [michael-buschbeck/mychs-macro-magic#78] opened 2021-04-14 17:42 UTC
We're asking for more and more features to be built into MMM (such as roll table support #76 and exposing the turn tracker #40), and so far existing API scripts mostly had some deficiency or another that made it not just convenient for the MMM user but also necessary to ask for these features. In the long run, however, it seems like a waste of developer time to not be able to use existing API scripts from within MMM -- as, for example, in the case of Spawn which could easily do what I need in [MGD#3](https://github.com/phylll/mychs-macro-magic/issues/3), if only there was a way to call it *only* when needed from within an MMM script.

Does it make sense to think about a general way to provide access to other installed API scripts?

From line 330 onwards in [Spawn](https://github.com/djmoorehead/roll20-api-scripts/blob/master/Spawn%20Default%20Token/SpawnDefaultToken.js), I'm getting the notion that it appears to be possible to check for the existence of other API scripts via some object they instantiate, and to use those and let them do something. I have no clue whatsoever if this could actually work for our needs, though, or if it would be too messy in some way.

**Comment by michael-buschbeck** [comment] 2021-04-15 13:13
I believe you ought to be able to do this right now already:

| Line | Script
|-|-
| 1 | _!mmm_ **chat:** !spawn whatever

Does that work?

As for checking another API script's presence: It's all just one big JavaScript namespace in there for all concurrent scripts – anyone can just look if some known object exists (e.g. the `MychScript` class), call stuff on it, read stuff from it, _change_ stuff in it, or even monkeypatch it.

So if there's a known other API script we want to call a certain internal function of, we certainly could.

In general, though, an API script's user interface is through its custom chat message parser. You might be tempted to think that Roll20 might supply some generalized command-line parser for API scripts to use or at least some global registry of `!foo` prefixes to dispatch to, but that's not the case – every API script sees every single chat message (not even limited to messages starting with `!`) and can decide at will whether and what to do about them.

So, using a script to send a message to chat that starts with `!spawn` should have the same effect as if a user had sent a `!spawn` message to chat.

**Comment by phylll** [comment] 2021-04-15 13:44
Nope, that doesn't work.

**Comment by phylll** [comment] 2021-04-15 13:45
You can use this line for testing in the TEST game, should work for all players and characters:

`!mmm chat: !Spawn --name|TestStuff --offset|1,-1 --side|2`

**Comment by michael-buschbeck** [comment] 2021-04-15 17:24
Interesting! I'll try to figure out why that is. Possible outcomes:

- Something's wrong in the way chat messages MMM sends through `sendChat()` are set up that I _can_ control – then I'll just fix it.

- Dito in a way that I _can't_ control – then I'll try to find out if I can call `on("chat:message")` handlers without going through `sendChat()` with a `msg` data structure entirely of my design.

**Comment by michael-buschbeck** [comment] 2021-04-15 17:27
Actually – if I can find a way to "fake" the entire `msg` structure towards chat handlers, this would open up possibilities such as being able to fake `selected` for the invoked API through the invoking MMM script as well…

**Comment by michael-buschbeck** [comment] 2021-04-16 18:21
When I run the `!mmm chat: !Spawn ...` command quoted above, the sandbox crashes with this stack:

```
TypeError: Cannot read property 'who' of undefined
    at handleInput (apiscript.js:5587:43)
```

The chat message `msg` struct generated by MMM containing the `!Spawn` command has this content:

```
"chat:message type: api, playerid: API, who: Noffi Aeppler, target: undefined, target_name: undefined"
"chat:message content: !Spawn --name|TestStuff --offset|1,-1 --side|2"
"chat:message rolltemplate: undefined
```

This is certainly triggered by the `!Spawn` chat command having been generated through `sendChat()`, but also an error specific to the Spawn API script itself.

To add... more injury to injury, the error we're seeing in the stack trace is caused by a bug in Spawn's error reporting code, in [line 1648](https://github.com/djmoorehead/roll20-api-scripts/blob/d5f031a192ecfd0df34aaf7cdffa34fd239ad0af/Spawn%20Default%20Token/SpawnDefaultToken.js#L1648), which operates under the assumption that the `data` object has already been initialized, which obviously can't be relied on there.

**Comment by phylll** [comment] 2021-04-16 18:36
Ok ... but the very same Spawn command works if entered in the chat by itself, right? That is, at least, the behavior I observed using Yorric. Just making sure that the problem isn't somehow related to Noffi Aeppler (who may not be a character) sending this command.

**Comment by phylll** [comment] 2021-04-16 18:41
Another observation: Spawn isn't the first API script that crashes the sandbox when called through MMM. I think I've observed the same with some of the other scripts that our GM uses and that I've tried out to understand what he's doing manually, such as !rtm, !group-init and some other. That's the source of my prior conviction that it's impossible to call API scripts through the MMM `chat` command. So there appears to be a common type of problem, perhaps also with these API scripts...

**Comment by michael-buschbeck** [comment] 2021-04-16 18:43
It does. The problem lies in [line 1493](https://github.com/djmoorehead/roll20-api-scripts/blob/d5f031a192ecfd0df34aaf7cdffa34fd239ad0af/Spawn%20Default%20Token/SpawnDefaultToken.js#L1493) where Spawn blindly assumes it can look up a player whose ID is `msg.playerid`, but for `sendChat()`-produced chat messages, `msg.playerid` is the string `"API"`.

(To be fair, MMM does something very similar in one place, too: in `whisperback()`.)

**Comment by michael-buschbeck** [comment] 2021-04-16 18:53
So right now I'm not sure if there's _any_ way for MMM to call other API scripts' chat message event handlers outside of using `sendChat()` – which makes `msg.playerid` be `"API"`, which apparently many API scripts crash on.

The problem is that these chat message event handlers are typically created and registered like so:

```
on("chat:message", function() { ... });
```

...as an anonymous function that can't be referenced by anyone who doesn't have an explicit reference to it.

**Comment by phylll** [comment] 2021-04-16 18:58
I see. So the alternatives would be having to write specific "gateways" to other API scripts that would use their classes directly, without using the chat message API, or reimplementing any functionality we might need ourselves inside MMM?

**Comment by phylll** [comment] 2021-04-16 20:30
In this particular case of Spawn, however, isn't there a named method `SpawnDefaultToken.handleInput()` (called [here](https://github.com/djmoorehead/roll20-api-scripts/blob/d5f031a192ecfd0df34aaf7cdffa34fd239ad0af/Spawn%20Default%20Token/SpawnDefaultToken.js#L1653)) which we could call?

**Comment by michael-buschbeck** [comment] 2021-04-16 22:11
If I read this right, `handleInput` is a local in an anonymous function (declared with the`() => { … }` syntax) that's called immediately after construction, then discarded. `SpawnDefaultToken` is assigned the return value of calling that anonymous function; I can't see a ` return` statement on that level, so I assume the return value is `undefined`. (I'll verify that next opportunity.)

Spawn's comments slider to an idea I had been pondering: A script can create a chat command button with arbitrary payload; when the user clicks that button, its payload executes as the user themselves, not `"API"`.

**Comment by michael-buschbeck** [comment] 2021-04-17 08:44
One _awfully_ hacky thought I had over night: I could try to replace the sandbox's `on(event, handler)` function with my own, make my own record of all chat message handlers that are registered, and then forward them to the original `on()`.

Not sure if that'll work – as you have seen in Spawn's source, JavaScript has grown constructs like `const` meanwhile.

**Comment by phylll** [comment] 2021-04-17 10:42
> If I read this right, `handleInput` is a local in an anonymous function (declared with the`() => { … }` syntax) that's called immediately after construction, then discarded. `SpawnDefaultToken` is assigned the return value of calling that anonymous function; I can't see a ` return` statement on that level, so I assume the return value is `undefined`. (I'll verify that next opportunity.)

Ah, then I misread the brackets there. Thanks for explaining!

As to the other ideas: while they both sound cool, I wonder if it wouldn't be easier, faster and less exposed to potential downstream risks to simply patch the API scripts we use in how they find the `playerid` or whatever they need. Most of these scripts don't seem to be under very active development, so in many cases we won't have to re-patch the next version very often. Or we'd submit our patches to the authors and get at least some of them accepted. We're not talking about a LOT of API scripts here, after all.

**Comment by michael-buschbeck** [comment] 2021-04-17 17:23
A few quick experiments:
- `SpawnDefaultToken` is present but `undefined` as expected :(
- But amazingly enough, I _can_ monkeypatch `on(event, handler)`, and I really do get hands on subsequently registered API scripts' event handlers!

**Comment by phylll** [comment] 2021-04-17 18:00
Wow. Does that mean the order of registration now becomes a major issue?

**Comment by michael-buschbeck** [comment] 2021-04-17 20:38
The (very simple) easy I tested this it'll only affect API scripts loaded (actually: run) after MMM. There may be a more subtle way that avoids this, but I'll have to investigate a bit more to be able to say.

Order of API scripts seems consistent at least even if it can't be conveniently changed – same as Rollable Table entries.

**Comment by michael-buschbeck** [comment] 2021-04-24 17:05
I was just about to type a summary of why this won't ever work satisfactorily when I had a sudden idea.

As stated above, the usual problem with calling other API scripts via _!mmm_ **chat:** is that API scripts often attempt to look up the player who sent the command by looking up the `msg.playerid` of the intercepted chat message, which (unfortunately) is `"api"` for any chat message sent through MMM.

We can monkeypatch the `on("chat:message", handler)` Roll20 API function to intercept it and impersonate Roll20 to registered handlers, but this will only ever affect scripts loaded _after_ MMM.

But… we could monkeypatch `getObj()` and `findObj()` – and then have them return the actual sender's player object when asked for a `"player"`-type object with ID `"api"`…

Maybe this won't fix every other API script, but it might fix _some_. Worth a try maybe?

**Comment by phylll** [comment] 2021-04-24 17:25
Sounds very hacky but very cool. And maybe not a LOT of work to give a try?

**Comment by michael-buschbeck** [comment] 2021-04-24 17:47
Should be easy enough to set something up to play around with. :)

We could even go for a hybrid approach where we do the `getObj()` hack in any case but also hijack `on("chat:message")` to wrap handlers in an interceptor that replaces `playerid: "api"` with the correct player ID before the original handler even sees anything different.

That way, scripts loaded _after_ MMM get the luxury guaranteed-to-work treatment, and anything loaded _before_ MMM still hs a fighting chance.

**Comment by phylll** [comment] 2021-04-24 18:11
Since you said earlier that the order of scripts "seems consistent" -- is it one we can influence outside MMM, e.g. by simply installing MMM as the first script in our game, and all the others thereafter? Maybe this is too banal but just checking...

**Comment by michael-buschbeck** [comment] 2021-04-24 20:13
That's my impression, yes.

In our test game, I first created `TestMych.js`, then MMM, and after that various other API scripts were added over time. The placement of the first two has remained consistent so far.

It seems like moderately good UX to always show (and load) API scripts in the same order, so the consistent order we've been observing might not even be accidental. (And that it can't be conveniently changed might be due to the order _nominally_ not being significant.)

**Comment by michael-buschbeck** [comment] 2021-04-25 08:15
Just did an experiment that revealed that consecutive chat handlers actually get the **same** `msg` object.

So if MMM was registered before Spawn and MMM sends a `!Spawn` command, that command's `msg` structure will pass by MMM before Spawn's handler gets it, and MMM can very simply assign whatever it wants to `msg.playerid` (or any other part of the `msg` structure, for what it's worth).

So we won't even have to monkeypatch `on("chat:message")` and intercept handler registration to get to that point.

**Comment by michael-buschbeck** [comment] 2021-04-25 10:45
Using this Spawn command to test (because it nicely cleans up after itself):

```
!Spawn --name|TestStuff --offset|1,-1 --side|2 --expand|20,50,true
```

(For testing, I'd love to be able to do away with having to have a token selected, too, but I don't seem to be that lucky.)

**Comment by michael-buschbeck** [comment] 2021-04-25 11:05
Another wrinkle: Regardless of what's selected at the time `sendChat()` is called, it passes an undefined `msg.selected` to all chat handlers.

I can fix that the same way I can fix `msg.playerid`, but this means that the `getObj()`/`findObjs()` monkeypatching hack won't suffice for scripts registered before MMM (because selected tokens are passed in `msg.selected` and not queried through an API function I can patch).

**Comment by phylll** [comment] 2021-04-25 11:07
> Another wrinkle: Regardless of what's selected at the time `sendChat()` is called, it passes an undefined `msg.selected` to all chat handlers.

I'm pretty sure that I've seen other API scripts work based on multiple selections... maybe worth a bit of research how they manage doing that? I'll dig a bit and will update this reply if I find anything interesting.

**Comment by michael-buschbeck** [comment] 2021-04-25 11:10
You may have misunderstood: MMM has no trouble getting to `msg.selected` when called directly, and I don't expect any other API script to have any more trouble when called directly.

But when MMM uses `sendChat()` to send an API script command to another API script, the `msg` data structure created by `sendChat()` to pass on to the other API script will have `msg.selected == undefined` regardless of what was selected.

**Comment by phylll** [comment] 2021-04-25 11:14
Aaah. Indeed, I misunderstood. Thanks! While inelegant and potentially the source of much headscratching if we ever forgot about it and set up a new game (or for others using MMM in the future), from a practical perspective it doesn't seem a big problem if we'd have to rely on "subordinate" scripts to be installed after MMM in our games.

**Comment by michael-buschbeck** [comment] 2021-04-25 11:24
I tend to agree, especially since the `getObj()` hack doesn't guarantee that API scripts want to use `msg.playerid` for something else as well, so it's (even more) fragile at best.

I've installed MMM 1.18.0-pre-4 in our test game that has (currently experimental) support for invoking other API scripts through the _!mmm_ **chat:** command. For me, this work like a charm now:

| Line | Command
|-|-
| 1 | _!mmm_ **chat:** !Spawn --name\|TestStuff --offset\|1,-1 --side\|2 --expand\|20,50,true

**Comment by michael-buschbeck** [comment] 2021-05-02 14:06
One (intrinsic) complication: When MMM modifies a message directed at an(other) API script, that message is essentially anonymous – all MMM can see is that it was sent by a `sendChat()` call, but any other context (which player sent it? which script sent it?) is lost. (Which is why we're having this issue in the first place.)

MMM currently solves this ambiguity by prefixing and suffixing the intended API chat message with dummy `sendChat()` messages with callbacks ([see docs](https://help.roll20.net/hc/en-us/articles/360037256754-API-Chat#API:Chat-sendChat(speakingAs,input[,callback[,options]]))) that set/unset the desired impersonation state in a global variable for MMM to pick up when an API message comes in. Given that code running in the API sandbox is single-threaded, these three consecutive `sendChat()` commands can't be preempted by any other API-sent API script commands, so this should be safe.

An alternative implementation (with its own disadvantages) could be this: MMM could modify the (MMM-sent) API script command by prefixing it with e.g. `!mmm impersonate <playerid>`, then interpret this prefix and strip it when it comes back through the MMM chat handler. The disadvantages of this approach are that it'll be harder to secure (might need to pass a sufficiently random identifier instead of plain `<playerid>` to avoid users abusing this), and it totally prevents API scripts that were registered _before_ MMM from ever getting their MMM-sent API script commands.

**Comment by michael-buschbeck** [comment] 2021-05-02 16:20
I'm declaring this an enhancement/bug – not a bug strictly within MMM but one in the whole complex of MMM and other API scripts collaborating through the Roll20 infrastructure.

**Closed** 2021-05-02 18:50 UTC
Labels: bug, enhancement
